name: GitHub Actions Vercel Production Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Install dependencies
        run: npm ci
      - name: Temporarily rename pnpm-lock.yaml
        run: mv pnpm-lock.yaml pnpm-lock.yaml.backup
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Restore pnpm-lock.yaml
        run: mv pnpm-lock.yaml.backup pnpm-lock.yaml
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}